### ISSUE TITLE
Test framework does not honor "Configure Property"

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.Testing#1]
Raised by @mauroservienti
Migrated from by https://github.com/Particular/NServiceBus/issues/2164

given the following gist:
https://gist.github.com/Romiko/9b16a183753095d579bb

it appears that the ConfigureProperty calls at lines 28 and 30 in the Initialize.cs file are not respected.

**Comment by johnsimons** [comment]
This will be fixed as part of https://github.com/Particular/NServiceBus/commit/dedafedbdac179667171fb9ecdbdaa7fe66749b4
