### ISSUE TITLE
Add ExpectTimeOutNotSet in saga test

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.Testing#10]
Raised by @mastoj
Migrated from by https://github.com/Particular/NServiceBus/issues/1656

I would like to test a saga that a timeout has not been set, but that is not possible with the curren testing api. Ref. http://stackoverflow.com/questions/19221796/is-it-possible-to-test-an-nservicebus-saga-that-a-timeout-has-not-been-set/.

**Comment by timbussmann** [comment]
This will be possible with the v6 release of NServiceBus.Testing where you can use `ExpectNoTimeoutToBeSetIn`. @SimonCropp are you good with closing this issue then?

**Comment by timbussmann** [comment]
(wrong button)
