### ISSUE TITLE
Obsolete AssertSagaCompletionIs in favor of ExpectSagaToBeCompleted?

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.Testing#100]
AssertSagaCompletionIs is the only method that is an "assert" and there for needs to be called after the "When". All others are ExpectX.

See https://github.com/Particular/docs.particular.net/pull/2348/commits/94637d4319e5781139f5f01a3356e6bd7322b6c4

Note how confusing the mix is:

```
                 .ExpectPublish<MyOtherEvent>() //publish should happen on timeout
                  .WhenSagaTimesOut()
                  .AssertSagaCompletionIs(true); //saga should be completed on timeout
```

**Comment by timbussmann** [comment]
makes a lot of sense to me 👍 can we introduce the expect version without a breaking change side-by-side to the assert?

**Comment by andreasohlund** [comment]
Yea, that should be possible

**Comment by danielmarbach** [comment]
👍 for side by side and obsolete the old with warn

**Comment by timbussmann** [comment]
planning this for a 6.1 minor then.

**Comment by timbussmann** [comment]
changing the milestone to v7

**Comment by bording** [comment]
I assume there are some docs changes required for this?

**Comment by timbussmann** [comment]
@bording that's correct. I raised a PR here: https://github.com/Particular/docs.particular.net/pull/3284
