### ISSUE TITLE
Make asserting on message type easier for interface messages

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.Testing#101]
Currently users have to know that we generate impl types for interfaces  and use `.IsAssignableFrom`

This will fail

`Assert.IsType<IExportFileArrivedInSourceFolder>(session.PublishedMessages[0].Message);`

this is the correct syntax

`Assert.IsInstanceOf<IExportFileArrivedInSourceFolder>(session.PublishedMessages[0].Message);`

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/particularsoftware/NOetP7nsHhg/oFr4NbMQAwAJ

**Comment by andreasohlund** [comment]
Another way to do this is

```
Assert.AreEqual(1, session.PublishedMessages
.Containing<IExportFileArrivedInSourceFolder>().Count());
```

Is there a way we can improve this?

**Comment by danielmarbach** [comment]
Like you pointed out the assertion is wrong. We publish a concrete type like you explained. Isn't that normal csharp behavior. Assuming the code would look like this:

Publish<IExportFileArrivedInSourceFolder>(new ExportFileArrivedInSourceFolder());

would you expect the assert to succeed? 

We would need to see if we can trick the proxy to lie to the user by claiming it is the interface type. Not sure that would even work and might break other scenarios.

**Comment by timbussmann** [comment]
as stated in the involved discussions, I think the approach to use `Assert.IsInstanceOf` is the correct way to write that assertion from a language perspective (because no message will ever succeed that check.

Also, the alternative solution is a nice way to write the test so I don't think we should do something about this. Vote to close.

**Comment by andreasohlund** [comment]
My idea was a `.MessageType` property but that wouldn't be bullet proof since the user would have to find it and make use of it.

Ok to close
