### ISSUE TITLE
Static nature of Test.Initialize prevents parallel tests

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.Testing#11]
Raised by @SimonCropp
Migrated from by https://github.com/Particular/NServiceBus/issues/1321

Since `Test.Initialize` sets some static state it effectively prevents us from running tests  in parallel https://github.com/NServiceBus/NServiceBus/blob/master/src/testing/Test.cs#L37

**Comment by johnsimons** [comment]
@Particular/nservicebus are we ever going to revamp the testing framework and remove statics?
Should this be a requirements issue?

**Comment by andreasohlund** [comment]
+1 for creating a big picture plan of attack in requirements

**Comment by johnsimons** [comment]
We are working on a plan of attack to tackle issues like this.
