### ISSUE TITLE
Add WhenHandling accepting a message as a parameter

### ISSUE THREAD

**Issue by DixonDs** [Particular/NServiceBus.Testing#119]
In some cases, `WhenHandling<TMessage>(Action<TMessage> initializeMessage = null)` can't be used because the message had read-only properties set in ctor. It would be nice to have another overload `WhenHandling<TMessage>(TMessage message)` allowing to pass a constructed message.

**Comment by mikeminutillo** [comment]
You can use one of the overloads of `When(..)` to do this:

```csharp
var message = new SomeMessage()

testSaga.When((saga, context) => saga.Handle(message, context));

// OR

testSaga.When(saga => saga.Handle, message);
````

**Comment by DixonDs** [comment]
@mikeminutillo yes, it is just that `testSaga.WhenHandling(message)` is a bit more readable than `testSaga.When((saga, context) => saga.Handle(message, context));` and it doesn't require the `Handle` method to be created at the point when you write a test so it is a bit more convenient for test-first development.

The point being, it is not a big deal to use just `When`, but since we already have `WhenHandling`, probably it won't do much harm if another overload is added. What do you think?

**Comment by timbussmann** [comment]
@DixonDs the next major release (v7) will contain a new `WhenHandling` overload implemented by @mikeminutillo to address this. Thanks for raising this issue 👍
