### ISSUE TITLE
Add a overload to WhenSagaTimesOut that excepts a timespan

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.Testing#12]
Raised by @andreasohlund
Migrated from by https://github.com/Particular/NServiceBus/issues/648

The WhenSagaTimesOut releases all timeouts. It can be interesting to "release all timeouts up to this time" so we should add an optimal timespan argument.

We could also look into a separate method:

.WhenTimeHasPassed(TimeSpan.FromDays(2))

**Comment by timbussmann** [comment]
closing this one, as v6 will support this by `WhenSagaTimesOut(TimeSpan? after = null)`
