### ISSUE TITLE
ExpectSend not checked when sending to specific destination (v5)

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus.Testing#122]
related to this SO question: https://stackoverflow.com/questions/47170203/nservicebus-unit-testing-expectsend-not-fullfilled-when-bus-send/47265190

When sending a message to a specific destionation in v5 like this:  `bus.Send(EndPointName.SpmAuditLogService, goodsReceiptAuditCommand);`, `ExpectSend` tests are not checked. This means that a test using `.ExpectSend<GeneralLedgerAuditCommand>()` will fail. Users have to use `ExpectSendToDestination<GeneralLedgerAuditCommand>` instead, which is not obvious.

v6+ is not affected, as `ExpectSend`s are properly invoked, even when sending to a specific destionation.

**Comment by danielmarbach** [comment]
V5 is only supported with extended support. Closing this
