### ISSUE TITLE
Improve the support for unobtrusive mode when unit testing

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.Testing#13]
Raised by @andreasohlund
Migrated from by https://github.com/Particular/NServiceBus/issues/655

Today you have to do this:

```c#
MessageConventionExtensions.IsMessageTypeAction =
                t => t.Namespace != null && t.Namespace.EndsWith("Messages") && !t.Namespace.StartsWith("NServiceBus");

Test.Initialize();
````
We should improve this so that users can pass in the conventions to test initialize or similar

**Comment by andreasohlund** [comment]
Fixed in v5 since you can pass in the conventions in Test.Initialize

https://github.com/Particular/NServiceBus.Testing/blob/develop/src/NServiceBus.Testing/Test.cs#L29

**Comment by andreasohlund** [comment]
Updating doco in a separate pull
