### ISSUE TITLE
HandleCurrentMessageLaterWasCalled not marked as obsolete

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.Testing#130]
```
System.NotSupportedException : HandleCurrentMessageLater has been deprecated and will be removed in NServiceBus.Core Version 8.
   at NServiceBus.Testing.TestableInvokeHandlerContext.get_HandleCurrentMessageLaterWasCalled()
```

**Comment by timbussmann** [comment]
Hey @SimonCropp,
Would you expect a different behavior given that the `HandleCurrentMessageLater` cannot be used anymore with v7?

**Comment by SimonCropp** [comment]
I think an obsolete with error would be sufficient

**Comment by timbussmann** [comment]
ah I see. Agreed, it should be marked as obsolete, seems like we just missed that. I think that's an easy fix for the next minor. @Particular/nservicebus-maintainers any concerns in regards to the "braking change" (potentially breaking compilation of an API call which throws anyway)?

**Comment by andreasohlund** [comment]
If we obsolete with WARN we should be fine?

**Comment by SimonCropp** [comment]
why would u obsolete with warn, only to throw at runtime?

**Comment by andreasohlund** [comment]
Thinking to avoid a breaking change?

**Comment by SimonCropp** [comment]
But it is already broken. There is no value in only warning

**Comment by timbussmann** [comment]
as it should only affect test code, I don't see a huge risk to introduce a potentially breaking compilation error imo.

**Comment by bording** [comment]
Given that calling the method already throws at runtime, it seems reasonable to me to go ahead and just add the correct obsolete here.

**Comment by SimonCropp** [comment]
or u could just bump the major

**Comment by SimonCropp** [comment]
just got bit by this in another project. what is the hold up on this one? unless i am mistaken it it 1 line of code

**Comment by timbussmann** [comment]
Hey @SimonCropp. The plan is to fix this with the next minor release. Do you feel there is a higher urgency to address this instead?

**Comment by SimonCropp** [comment]
depends what the ETA on the next minor is?

**Comment by timbussmann** [comment]
I'm not aware of any ETA for the next minor at the moment :/
