### ISSUE TITLE
How to inject a bus via constructor injection 

### ISSUE THREAD

**Issue by TraGicCode** [Particular/NServiceBus.Testing#131]
Is constructor  injection not supported? Is the only option making it a public property?

**Comment by andreasohlund** [comment]
Constructor injection is supported across the board. Are you trying to test a saga or a message handler?

**Comment by andreasohlund** [comment]
@TraGicCode is this still an issue for you?

**Comment by TraGicCode** [comment]
Hey @andreasohlund ,

Let me get back with you tommorow on this.  Thank you
