### ISSUE TITLE
INeedInitialization gets invoked when Test.Initialize() is called

### ISSUE THREAD

**Issue by sfarmar** [Particular/NServiceBus.Testing#16]
As per @andreasohlund, that is not the expected behaviour

We have an open case with a customer https://nservicebus.desk.com/agent/case/7380

https://groups.google.com/forum/#!msg/particularsoftware/iF1fT_oVfb4/boT0MXgiik0J

**Comment by johnsimons** [comment]
@Particular/engineers do we fix this, or is this working as expected ?

**Comment by andreasohlund** [comment]
I'd say it needs to be fixed since we guide users to use `INeedInitialization` and things done in there can't be assumed to be "safe for unit testing"

**Comment by danielmarbach** [comment]
Have we really thought that through. Usually RegisterSteps are registered in `INeedInitialization` what if the users expect those to be registered?

**Comment by danielmarbach** [comment]
Furthermore the creation and invocation of the `INeedInitialization` is backed into the core :(

**Comment by andreasohlund** [comment]
@timbussmann did you by any chance fix this in the v6 upgrade?

**Comment by danielmarbach** [comment]
@andreasohlund Based on what I saw in my reviews yes because we are using a totally different approach.

**Comment by danielmarbach** [comment]
Can we add a new milestone for the next release, assign this issue and then close it?

**Comment by andreasohlund** [comment]
Done

**Comment by timbussmann** [comment]
`Test.Initialize()` is gone in v6 and unit tests won't invoke `INeedInitialization` any more.
