### ISSUE TITLE
Add support for arrange,act, assert(AAA) style testing for sagas and handlers

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.Testing#2]
Raised by @andreasohlund
Migrated from by https://github.com/Particular/NServiceBus/issues/654

Add overloads to allow AAA style testing of sagas.

```
Test.Saga<PreferedCustomer.Policy>()
    .Given(g =>{
           g.Message<OrderAccepted>(m=>{m.OrderValue = 1000;m.OrderId="xyz";);
           g.Timeout<OrderNoLongerValidForBonus>(t=>t.OrderId = "xyz")
           }
    )
   .When<OrderAccepted>(m=>m.OrderValue = 4999)
   .ShouldNotPublish<CustomerMadePrefered>();
```

We'll also look into checking the mappings by making sure(Perhaps a option: strict) that the messages in "Given" actually has started a saga and the following messages have correlated to to that saga instance.  In the example above that would mean that the user would have to add a CustomerId to correlate the orders on.

**Comment by jole78** [comment]
Is this feature still worked upon?

I can give you my comments on how I think about AAA style testing.

I "other" frameworks that uses Mocks/Stubs (let´s take FakeItEasy as an example) I can do the following:

// arrange
Setup the mocks and other things that are considered "givens"
::Create the SUT (system under test) with mocks
message = new NativeMessage { Content = new byte[0] };

// act
::Perform the action on the SUT (system under test)
SystemUnderTest.Handle(message);

// assert
::Use the Mocks to make sure that the SUT called any of the mocks with the things I expected it to.
A.CallTo(() => Validator.Validate(A<string>.Ignored, A<string>.Ignored)).MustHaveHappened();

In NSB Testing I´m forced to have the assert (.ExpectPublish....) before the act (.OnMessage...)
           Test.Handler(bus => new MyHandler(bus, FakeValidator))
                .ExpectPublish<MyEvent>(m => true)
                .OnMessage<NativeMessage>(new NativeMessage { Content = new byte[0] });

From what I can see OnMessage will clear all the expects after it runs....
Preferably I would like to:
Setup the handler in the ARRANGE with the fakes etc (this is possible today)
Use OnMessage in the ACT and have it "save" what it did
Use ExpectPublish in the ASSERT and make sure it actually published the message

**Comment by SimonCropp** [comment]
moving forward we will be balding a less opinionated testing lib. people can (or not) use AAA if they desire
