### ISSUE TITLE
Better exception message when forgetting to specify conventions

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.Testing#23]
Users making use of unobtrusive mode will now get 
`Could not find a concrete type mapped to MPS.LoC.BoardAccountService.Events.IBoardingStartedEvent` 
if they forget to specify conventions.

Full discussion here https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/particularsoftware/ChY48v9ohPE/MHHSGTVULhgJ

**Comment by timbussmann** [comment]
message conventions will no longer be necessary for unit testing in v6. Are you good with closing this one @andreasohlund?
