### ISSUE TITLE
Update to NSB v6

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus.Testing#29]
Taskforce: @timbussmann @mat-mcloughlin  @szymonpobiega @WojcikMike

### Impact assessment
We need to update the testing package to support v6 of NServiceBus to allow users to migrate to v6 when they rely on the testing framework.
Within the last 6 weeks the testing packages were downloaded around 4000 times from nuget (all versions), compared to 16k total downloads on NSB.Core. It's difficult to estimate usage by users, but that suggest that quite a few users make use of the testing framework.

### Plan of Attack

* [x] Update to v6 core (asynx & handler context)
* [x] Simplify testing infrastructure by removing starting the entire endpoint
* [x] Provide testable fake implementations for context classes
* [x] Provide description and readme for the repo
* [x] update docs & samples
* [x] Figure out testing story for `SynchronizedStorageSession` (NHibernate + RavenDB)
* [x] Potentially make public classes partial
* [x] Move fake tests from Testing to Core

**Comment by hmemcpy** [comment]
Should we consider postponing refactoring the Test API, now that we've upgraded it to v6? Can this wait until after v6 ships?

**Comment by mat-mcloughlin** [comment]
If this is the case we still need to look at docs and samples

**Comment by hmemcpy** [comment]
Here are the notes from our sync, with things to work on next:

  - Improve the error messages upon failure
    - Provide additional information on test failure (serialized SendOptions?)
    - More sensible output (consider throwing an exception instead of using Fail())
  - Improve test initialization
    - Provide saga data to the saga initializer
  - Update nuget packages to the latest
  - Add an overload to the invocations that takes in the SendOptions (in addition to Check func)
  - Check (and possibly remove) some obsoletes, provide guidance on what to do instead
    - Additional downstreams?
    - Callback and Gateway packages
  - Split the Handler and Saga test classes?
  - Saga timeout
    - Check if we can have a test for timeout in v6
    - Add expect methods for set periods of time (ask/blame Mat about his TimeSpan idea!)
  - Make it thread-safe
    - Make sure the TestableHandlerContext is thread-safe (collection access)
  - Improve assertions
  - Raise an issue to "obsolete" the testing framework in favor of an acceptance test framework that is centered around the endpoint
  - Docs
    - Raise the changes on the docs sync
    - Add a chapter/NOTE: for the changes in the framework (not starting the endpoint, no assembly scanning, no need to do initialization)

**Comment by weralabaj** [comment]
@hmemcpy @mat-mcloughlin do you need some help on that? I know ppl looking for work so ping me in tomorrow morning on Slack if you can delegate anything.

**Comment by SzymonPobiega** [comment]
Dear TF, do you need any help?

**Comment by timbussmann** [comment]
@SzymonPobiega It looks like most implementation work is done at the moment and we're heading for documentation/story production. If you want to get involved there feel free to join on the tf-v6-testing slack channel :)

**Comment by timbussmann** [comment]
Status update: 
Moved fake implementations to core and added source package to NServiceBus.Testing
Working on samples
Fixing minor bugs, spelling errors, misaligned formats and so on.

**Comment by mat-mcloughlin** [comment]
Status update:

- Fixed race condition with timeouts (pending review)
- Started to dogfood the new fakes in core

**Comment by mat-mcloughlin** [comment]
Given the need to get this task completed as soon as possible is it worth considering splitting the NHibernate and Raven fakes into a separate issue?

Also do we still need a story regarding this or is the plan to add something small as part of a bigger v6 story?

**Comment by timbussmann** [comment]
> Also do we still need a story regarding this or is the plan to add something small as part of a bigger v6 story?

I added a section to the handler context story about writing "traditional unit tests" with v6.

> Given the need to get this task completed as soon as possible is it worth considering splitting the NHibernate and Raven fakes into a separate issue?

I still think it's part of this issue and needs to be done

**Comment by timbussmann** [comment]
All tasks from the PoA have been addressed. Closing this issue.

![](http://media0.giphy.com/media/GCLlQnV7wzKLu/giphy.gif)

**Comment by danielmarbach** [comment]
Great stuff!

**Comment by mat-mcloughlin** [comment]
Happy days
