### ISSUE TITLE
ExpectTimeoutToBeSetAt not working

### ISSUE THREAD

**Issue by sfarmar** [Particular/NServiceBus.Testing#35]
Any Ideas why this test fails?
```
Test.Initialize();

            Test.Saga<ShippingSaga>(orderId)
                .ExpectTimeoutToBeSetAt<FedexTimedOut>((m, at) => at == DateTime.UtcNow.AddSeconds(15))
                .When(saga => saga.Handle(message));
        } 
```

Given this handler:

```
public void Handle(ShippOrder msg)
        {
            Data.OrderId = msg.OrderId;

            Data.OrderDetails = msg.ProductName + " " + msg.ShippingAddress;

            Data.SentToFedex = true;

            Console.WriteLine("Handeling ShippOrder command with id: {0}", msg.OrderId);

            Bus.Send<ShipToFedEx>(m => m.OrderId = msg.OrderId);
            
            RequestTimeout<FedexTimedOut>(TimeSpan.FromSeconds(15));
        }
```

Here is the error:

```
System.Exception : ExpectedDeferMessageInvocation<HelloWorld.Messages.Messages.FedexTimedOut,System.DateTime> not fulfilled.
Calls made:
SendInvocation<HelloWorld.Messages.Commands.ShipToFedEx>
DeferMessageInvocation<HelloWorld.Messages.Messages.FedexTimedOut,System.TimeSpan>

   at NServiceBus.Testing.ExpectedInvocation`1.Validate(ActualInvocation[] invocations) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Testing\Invocations.cs:line 27
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at NServiceBus.Testing.StubBus.ValidateAndReset(IEnumerable`1 expectedInvocations) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Testing\StubBus.cs:line 20
   at NServiceBus.Testing.Saga`1.When(Action`1 sagaIsInvoked) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Testing\Saga.cs:line 305
   at HelloWorld.Sagas.Tests.SagaTests.TimeoutTest() in C:\Code\Particular\Course.Exercises\Saga\HelloWorld.Sagas.Tests\SagaTests.cs:line 40```

**Comment by timbussmann** [comment]
I think you need to use `ExpectTimeoutToBeSetIn` when using TimeSpans for `RequestTimeout`

**Comment by mswieder** [comment]
Sean - I'm not sure your example is correct - are you certain the DateTime that results of TimeSpan.FromSeconds(15) and DateTime.UtcNow.AddSeconds(15) are the same?  Might they be executed at different times and therefore result in different values?  If so, you might want to create the DateTime for the event in the Test code and pass it in to the Saga with the ShippOrder message and have the Saga use it as the RequestTimeout input.

timbussmann - why do you think it needs to be ToBeSetIn and not TeBeSetAt?  What is the proscribed use case for each?

**Comment by timbussmann** [comment]
@mswieder ToBeSetIn accepts a function validating a TimeSpan whereas ToBeSetAt takes a function validating a DateTime. The testing framework does not calculate a DateTime for the timeout to be executed based on a TimeSpan input. This is for the exact reason you mentioned: DateTime.Now is never the same on the validation function as when you actually call RequestTimeout. If you provide a DateTime to the RequestTimeout function you need to validate the DateTime and if you provide a TimeSpan , you need to validate the TimeSpan.

**Comment by WilliamBZA** [comment]
@sfarmar It's quite likely that `DateTime.UtcNow` has progressed in terms of time (even if only by a couple ms) between the `ExpectTimeoutToBeSetAt` Func is executed, and when it is set by the handler.

Using a mockable `DateTime` implementation would make this easier to test. Another option is to switch to `TimeSpan` instead of `DateTime` as @timbussmann recommended.

**Comment by mswieder** [comment]
Alas - I just tried with SetAt and passed in a fixed DateTime and still get the failed validation that Sean posted above.

**Comment by sfarmar** [comment]
This works ok:

```
 var orderId = Guid.NewGuid();
            var message = new ShippOrder { OrderId = orderId };

            Test.Initialize();

            Test.Saga<ShippingSaga>(orderId)
                //.ExpectTimeoutToBeSetAt<FedexTimedOut>((m, at) => at == DateTime.UtcNow.AddSeconds(15))
                .ExpectTimeoutToBeSetIn<FedexTimedOut>((m, at) => at == TimeSpan.FromSeconds(15))
                .When(saga => saga.Handle(message));
```

**Comment by mswieder** [comment]
Alas, my issue is with .ExpectTimeoutToBeSetAt.  Are you able to get that working when you use a fixed DateTime and pass it in to the handler in the message?

**Comment by timbussmann** [comment]
@mswieder Locally both `ExpectTimeoutToBeSetAt` with a DateTime and `ExpectTimeoutToBeSetIn` with a TimeSpan work for me. Can you show us your saga, your test and the exception you receive?

**Comment by mswieder** [comment]
Well - I don't have an explanation for this, but mine is working now too.  Thanks all.  
Nothing to see here.

**Comment by WilliamBZA** [comment]
Using a fixed time works for me, DateTime.UtcNow.AddSeconds(15) doesn't work for me.

My current dev machine is under a bit of strain though.  Perhaps yours was too :)

**Comment by timbussmann** [comment]
> DateTime.UtcNow.AddSeconds(15) doesn't work for me

since you're providing a `DateTime` to `RequestTimeout` you also need to verify the `DateTime` using `ExpectTimeoutToBeSetAt` and I have no idea how you want verify that you added 15 seconds to `DateTime.Now` at some earlier point without mocking `DateTime` ;)

**Comment by timbussmann** [comment]
@sfarmar are you ok with closing this issue too?
