### ISSUE TITLE
Cannot use new Saga Scenario testing framework when Saga is derived from SqlSaga<TSagaData>

### ISSUE THREAD

**Issue by HScheenen** [Particular/NServiceBus.Testing#365]
A saga that is derived from SqlSaga<TSagaData> cannot be tested using the new Saga Scenario testing framework. The problem is that TestableSaga<TSaga, TSagaData> has a type constraint on TSaga which requires that TSaga is derived from NServiceBus.Saga<TSagaData>. Unfortunately, SqlSaga<TSagaData> derives from NServiceBus.Saga, making it impossible to fulfill the type constraint on TSaga.

Making SqlSaga<TSagaData> in NServiceBus.Persistence.Sql derive from Saga<TSagaData> would fix this problem. However, that could be a breaking change in NServiceBus.Persistence.Sql.

**Comment by danielmarbach** [comment]
Hi Herman,

Thanks for reaching out and letting us know about the shortcoming. Can you elaborate why you are using `SqlSaga` in those specific cases? As far as I'm aware, it is actually not required to use `SqlSaga` as a base class anymore. We have lifted the constraints mostly. 

> SqlSaga<T> is an alternate saga base class for use with SQL persistence that offers a less verbose mapping API than NServiceBus.Saga<T>. It's generally advisable to use NServiceBus.Saga<T> by default for most new projects

https://docs.particular.net/persistence/sql/sqlsaga

Regards,
Daniel

**Comment by HScheenen** [comment]
Hi Daniel,

Thanks for your quick reply. Sometimes the solution is just too obvious! We have no special reason to use `SqlSaga` as a base class, other than "that's how we always did it in the past". We'll change to `Saga` .  

Regards,
Herman
