### ISSUE TITLE
MarkAsComplete on a new saga instance throws exception

### ISSUE THREAD

**Issue by ngallegos** [Particular/NServiceBus.Testing#369]
Modifying [this test](https://github.com/Particular/NServiceBus.Testing/blob/master/src/NServiceBus.Testing.Tests/Sagas/BasicSaga.cs) with a call to `MarkAsComplete()` inside the OrderPlaced handler like so: 
```
public Task Handle(OrderPlaced message, IMessageHandlerContext context)
{
    Data.Placed = true;
    MarkAsComplete();
    return TimeToShip(context);
}
```
results in an Error:
> System.Exception : The saga should be retrieved with Get method before it's updated

**Comment by timbussmann** [comment]
Hi @ngallegos 

Thanks for raising this issue. We have confirmed this as a bug and added it to our backlog. It is eligible to be picked up for a future release, but we cannot provide a firm timeline.

**Comment by Tobias-08** [comment]
We have the same problem. This is blocking our adoption of the new saga scenario testing and I would appreciate a short-term fix.

**Comment by timbussmann** [comment]
This is being fixed with NServiceBus.Testing 7.4.1 which should be available on NuGet soon. Thanks for raising this issue!

**Comment by Tobias-08** [comment]
Thanks @timbussmann !
This fixed the issue on our side.
