### ISSUE TITLE
Order of Act and Assert statements

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.Testing#39]
A typical AAA style of testing implies the following order:
1. Arrange
2. Act
3. Assert

With NSB.Testing it is implied (mostly through suggestion on the google group) and a few [code snippets](http://docs.particular.net/nservicebus/testing/) that the proper order should be 
1. Arrange
2. Assert
3. Act / Assert (`AssertSagaCompletionIs()`)

The code doesn't actually always fail when used in "incorrect" way. Example:

```c#
        [Test]
        public void Should_work()
        {
            Test.Initialize();
            Test.Saga<SomeSaga>()
                .ExpectPublish<Finished>(e => e.InitialData == "123")
                .WhenHandling<SomethingHappened>(m => m.What = "123")
                .AssertSagaCompletionIs(true);
        }

        [Test]
        public void Should_not_work_for_inverted_order()
        {
            Test.Initialize();
            Test.Saga<SomeSaga>()
                .WhenHandling<SomethingHappened>(m => m.What = "123")
                .ExpectPublish<Finished>(e => e.InitialData == "123")
                .AssertSagaCompletionIs(true);
        }
```

**Comment by timbussmann** [comment]
changing the behavior of the order would have a significant impact on existing tests without really notifying the user about this (except that the tests just fail with a new version)?

With the easier testability for v6, users don't need to use the the fluent API and can write traditional unit tests instead, which follows the typical Arrange Act Assert order.

**Comment by SeanFeldman** [comment]
Wasn't aware of the change planned. 
After looking at the handler context pseudo code, it makes total sense.
Thank you @timbussmann
