### ISSUE TITLE
There should be a method for testing that no events was published

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.Testing#4]
Raised by @mastoj
Migrated from by https://github.com/Particular/NServiceBus/issues/770

To test that no side effects has occurred easier there should be a method for testing that no events was published. Something like:

```
        Test.Handler<OrderAcceptedHandler>()
            .ExpectNoEventPublished()
            .OnMessage<OrderAccepted>(m =>
                {
                    m.CustomerId = 1;
                    m.ProductId = 1;
                    m.OrderValue = 5000;
                });
```

**Comment by brunobertechini** [comment]
Reposting from https://github.com/Particular/NServiceBus.Testing/issues/7



One more thing I would like to add.

It would be usefull to have a way to test if no other invocation is made on send/publish/reply.

I would say : Test if this message will only publish the expected event and nothing else (publish/send/reply).

I would not suggest to assume that if we only expect one publish (ExpectPublish) means that we don't have anything else. One can have different tests for different behaviors.

I would suggest something like:

public Saga<T> ExpectNotPublishAnythingElse()
public Saga<T> ExpectNotSendAnythingElse()
public Saga<T> ExpectNotReplyAnythingElse()

So we can use it like this:

Test.Saga<MySaga>() 
.ExpectPublish<MyEvent>(evt => ....) 
.ExpectNotPublishAnythingElse() 
.ExpectNotSendAnythingElse() 
.ExpectNotReplyAnythingElse() 

This way (or something simmilar/same concept) will allow to explicitly validate not expected invocations added to handle method.

Apologies for the ugly names, but this is just to explain my point :)

Thanks a lot

Bruno

**Comment by dsaf** [comment]
This would be quite nice. I am surprised this is not supported yet. There is no way to work around this, so it will be a missing spot in my test cases unfortunately.

**Comment by timbussmann** [comment]
This can be easily achieved with the release of NServiceBus.Testing 6 using plain unit tests like this:

```
[Test
public async Task ExpectNoOutgoingMessages()
{
    var context = new TestableMessageHandlerContext();

    await handler.Handle(new SampleMessage(), context);

    Assert.IsEmpty(context.SentMessages);
    Assert.IsEmpty(context.PublishedMessages);
}
```

**Comment by dsaf** [comment]
@timbussmann Does it mean all the Expect(Publish/Send/SendLocal) method will be gone in 6.x?

**Comment by timbussmann** [comment]
@dsaf no worries, we still support the "Testing Framework" including the Expect methods in v6. For more flexibility and better integration (for example third-party mocking libraries) we want to offer a way to write more traditional style unit tests like the sample I posted above.

**Comment by dsaf** [comment]
@timbussmann I understand, thank you.

**Comment by andreasohlund** [comment]
@Particular/nservicebus-maintainers  Given that this is fully supported using [the new syntax ](https://github.com/Particular/NServiceBus.Testing/issues/4#issuecomment-213441043) I propose we close this as won't fix

**Comment by danielmarbach** [comment]
@andreasohlund @timbussmann @bording and I agree on this one. Closing
