### ISSUE TITLE
It's not possible to instantiate interface messages in AAA-style tests

### ISSUE THREAD

**Issue by kbaley** [Particular/NServiceBus.Testing#409]
We deprecated fluent-style tests but [someone pointed out](https://github.com/Particular/docs.particular.net/issues/5538) that we no longer have the ability to instantiate interfaces in AAA-style tests. There are [work arounds](https://docs.particular.net/nservicebus/testing/#testing-a-handler-interface-messages) and it's possible this use case isn't relevant any more but at this time, it looks like this is functionality that was deprecated without having a replacement in place.

We should investigate whether it still makes sense to allow instantiating interface messages in AAA-style tests. If so, implement it and if not, document the reasoning.

## Follow up channels

For completeness, let's add a comment to https://github.com/Particular/docs.particular.net/issues/5538 describing the outcome either way.

**Comment by timbussmann** [comment]
The docs page currently already describes how to use the `MessageMapper` to create dynamic implementations of interfaces: https://docs.particular.net/nservicebus/testing/#testing-a-handler-interface-messages so "not possible" doesn't seem to be the case.
