### ISSUE TITLE
Add ExpectSendToSites and ExpectNotSendToSites methods to Saga

### ISSUE THREAD

**Issue by chrisbednarski** [Particular/NServiceBus.Testing#42]
It's not possible to verify that a Saga under test sends messages over the gateway

**Comment by timbussmann** [comment]
Actually, it's also not possible to test SendToSites on message handlers with latest v5 versions. It will throw an exception instead.

**Comment by timbussmann** [comment]
I raised a PR to remove the `ExpectSendToSites` assertions which don't really work with the Gateway package. While this should be possible again with v6, I'm not sure how to solve this issue for v5. Any suggestions @Particular/nservicebus-maintainers @janovesk ?

**Comment by danielmarbach** [comment]
Here is a workaround I used before

```
public class MySaga : Saga<MySagaData>, IHandleMessage<Message>
{
    public void Handle(Message msg) {
       // do your normal stuff
       SendToSites(your params);
    }


    protected virtual void SendToSites(your params) {
       bus.SendToSites(your params);
    }
}
```

and the test

```
public class UnitTest
{
   [SetUp]
   public void SetUp() {
      testee = new TestableMySaga();
   }


   private class TestableMySaga : MySaga
   {
      public SendToSitesWasCalled { get; set; }


      protected override SendToSites(your params) {
          SendToSitesWasCalled = true;
      }
   }
}
```

Not beautiful but it works. See also 

https://groups.google.com/forum/#!searchin/particularsoftware/sendtosites/particularsoftware/xEYHQCUV2XA/cusZcPzCBQAJ

**Comment by timbussmann** [comment]
Closing this since we're not going to address this further in v5. While the workaround posted above isn't a good solution it helps to bridge the time between the v6 release which addresses this issue too.
