### ISSUE TITLE
Resetting fakes

### ISSUE THREAD

**Issue by oskar** [Particular/NServiceBus.Testing#446]
In some scenarios (integration testing) we re-use fakes between tests. It would be very useful to be able to reset/clear the fakes provided by this library, in particular `TestableMessageSession` and `TestablePipelineContext`, but the current design makes it difficult (only array copies of the message collections are exposed, not the internal `ConcurrentQueue` objects)

**Comment by SzymonPobiega** [comment]
Thanks for you feedback. We are going to take a look at it during the planning of the next release.

**Comment by DavidBoike** [comment]
I spiked this in https://github.com/Particular/NServiceBus.Testing/pull/517 but I'm not very happy with the result. Right now my preference would be to close this as won't fix. Take a look.

**Comment by DavidBoike** [comment]
I'm open to having my mind changed, but based on my reservations about the spike in #517 I'm closing this.
