### ISSUE TITLE
Handling Originator info with Testable saga

### ISSUE THREAD

**Issue by VitaliyLitovskyiSecurrency** [Particular/NServiceBus.Testing#456]
Hello,
We're creating scenario test with TestableSaga.
In saga under test there is logic that is sending message with SendOptions based on `IContainSagaData.Originator` property like the following:
``` 
  SendOptions options = new SendOptions();
  options.SetDestination(sagaData.Originator);
  ...
  await context.Send(message, options);
```
With current TestableSaga implementation it does not seem to be possible to set this property from test code. 
Data object is created at first attempt to load data https://github.com/Particular/NServiceBus.Testing/blob/master/src/NServiceBus.Testing/Sagas/TestableSaga.cs#L309
And after that it is loaded and saved inside TestableSaga only
For now we implemented hack that allows to set data properties via reflection but would like to find better solution. Could you please suggest something?

**Comment by timbussmann** [comment]
Hi @VitaliyLitovskyiSecurrency 

Thanks for raising this issue. This is indeed a bug in the `TestableSaga` implementation at the moment. There is already an open bug issue about this here: https://github.com/Particular/NServiceBus.Testing/issues/426. Looking at the issue, I've made a proposal to fix this via https://github.com/Particular/NServiceBus.Testing/pull/457 and I'll keep you updated about the status of that PR.

**Comment by timbussmann** [comment]
hey @VitaliyLitovskyiSecurrency , this should be fixed with NServiceBus.Testing 8.0.1 and 7.4.2, please give it a try

**Comment by AntoninaOstapovaSecurrency** [comment]
hi @timbussmann. Checked, that works. Big thanks)
