### ISSUE TITLE
Removing TestablePipelineContext in TestableMessageSession makes TestingExtensions incompatible

### ISSUE THREAD

**Issue by ogaute** [Particular/NServiceBus.Testing#533]
#### Description
In [this ](https://github.com/Particular/NServiceBus.Testing/pull/274/files#diff-918c55adc64d98fbe840b08654f7d428c9cf8bb40ca1801381d844da897925d4) PR , TestablePipelineContext where separated from TestableMessageSession

This makes the extension methods in [TestingExtensions](https://github.com/Particular/NServiceBus.Testing/blob/3215a2f981db1983c46d85d9d3c68319401af20a/src/NServiceBus.Testing/NSB.Testing.Fakes/TestingExtensions.cs#L14) incompatible when passing in TestableMessageSession as paramter.

`public static TMessage FindPublishedMessage<TMessage>(this TestablePipelineContext context) =>
            (TMessage)context.PublishedMessages.FirstOrDefault(msg => msg.Message is TMessage)?.Message;`

#### Expected behavior

Should be able to pass in TestableMessageSession as parameter in TestingExtensions  methods

#### Actual behavior

Not possible, because of removal of TestablePipelineContext 

#### Versions

NServiceBus.Testing 8.0.1

### Steps to reproduce

Install NServiceBus.Testing 8.0.1
Use extension on TestableMessageSession

#### Workarounds
Create local copy of extensions that take in TestableMessageSession as parameter

**Comment by danielmarbach** [comment]
@ogaute Thanks for bringing this to our attention for so many helpful details :+1: . I wasn't involved with the changes in the mentioned PR. I will try to dig a bit further. Could also have been an oversight on our end. I sent in a PR in case it was https://github.com/Particular/NServiceBus.Testing/pull/535. 

I'll keep you posted

**Comment by DavidBoike** [comment]
@ogaute the fix was just released in NServiceBus.Testing 8.1.0. [Announcement here](https://discuss.particular.net/t/nservicebus-testing-8-1-0-minor-release-available/3625).

**Comment by ogaute** [comment]
Nice, Thank you for solving it so quickly
