### ISSUE TITLE
Testing a Saga flow with multiple steps requires to repeat the setup for all of the steps instead of just the step in question

### ISSUE THREAD

**Issue by rmandvikar** [Particular/NServiceBus.Testing#599]
#### Description

If I have a Saga with multiple steps as
```
Start
Step1
Step2
Complete
```
where the flow is 
```
Start -> Step1 -> Step2 -> Complete
```
I should be able to test the scenarios is "slices", where I'm able to setup the pre-conditions for `Step2`, and test the
```
Step2 -> Complete
```
flow. 

With that, the tests are very maintainable, as for testing `Step2`, I only have to setup the preconditions for `SagaData` and assert the flows of `Step2`. 

Note that in the older version of `NServiceBus.Testing`, this was possible. 

I have given a simple example here. But note that in reality, the flow is bit complex with compensating actions at each of the steps if they fail. With this, I'm having to repeat quite a bit of setup code to test the later flows of the Saga as `Step2`, `Step3`, undo `Step2`, undo `Step3`, et al. 

```
Start ---> Step1 -------> Step2 ---------> Step3 ----> Complete
           | error        | error          | error       ^
      undo Step1 <-- undo Step2 <---- undo Step3         |
           |                                             |
           \--------------------------------------------/
```

#### Expected behavior

Unit test should should not throw and let the `IHandleMessages<T>`  type to proceed with the test, instead of only the `IAmStartedByMessages<T>` type. 

#### Actual behavior

Throws exception at line,

https://github.com/Particular/NServiceBus.Testing/blob/de28a2fdbc385fa8f15dc44167cdee07fab5b453/src/NServiceBus.Testing/Sagas/TestableSaga.cs#L328

#### Versions

NServiceBus 7.4.0
NServiceBus.Testing 7.4.2

Please list the version of the relevant packages or applications in which the bug exists.        

NServiceBus.Testing 7.4.2

### Steps to reproduce

Here is the Saga code:

```cs
public class TransactionSagaHander :
    NServiceBus.Saga<OrderSagaData>,
    IAmStartedByMessages<StartOrder>,
    IHandleMessages<Step1Order>,
    IHandleMessages<Step2Order>,
    IHandleMessages<CompleteOrder>
{
    protected override void ConfigureHowToFindSaga(SagaPropertyMapper<OrderSagaData> mapper)
    {
        mapper.MapSaga(saga => saga.OrderId)
            .ToMessage<StartOrder>(message => message.OrderId)
            .ToMessage<Step1Order>(message => message.OrderId)
            .ToMessage<Step2Order>(message => message.OrderId)
            .ToMessage<CompleteOrder>(message => message.OrderId)
            ;
    }

    public async Task Handle(StartOrder message, IMessageHandlerContext context)
    {
        Data.DramaProperty = "StartOrder";

        // work

        //return Task.CompletedTask;
        await context.Send(
            new Step1Order()
            {
                OrderId = message.OrderId
            });
    }

    public async Task Handle(Step1Order message, IMessageHandlerContext context)
    {
        Data.DramaProperty = "Step1Order";

        // work

        //return Task.CompletedTask;
        await context.Send(
            new Step2Order()
            {
                OrderId = message.OrderId
            });
    }

    public async Task Handle(Step2Order message, IMessageHandlerContext context)
    {
        Data.DramaProperty = "Step2Order";

        // work

        //return Task.CompletedTask;
        await context.Send(
            new CompleteOrder()
            {
                OrderId = message.OrderId
            });
    }

    public Task Handle(CompleteOrder message, IMessageHandlerContext context)
    {
        Data.DramaProperty = "CompleteOrder";

        // work

        //MarkAsComplete();
        return Task.CompletedTask;
    }
}

public class OrderSagaData :
    ContainSagaData
{
    public string OrderId { get; set; }
    public string DramaProperty { get; set; }
}

public class StartOrder : ICommand
{
    public string OrderId { get; set; }
}
public class Step1Order : ICommand
{
    public string OrderId { get; set; }
}
public class Step2Order : ICommand
{
    public string OrderId { get; set; }
}
public class CompleteOrder : ICommand
{
    public string OrderId { get; set; }
}
```

Here is the test that throws. 

```cs
    [Test]
    public async Task __Verify_Transaction_SagaData_Using_Testing_Previously()
    {
        var fixture = new Fixture().Customize(new AutoMoqCustomization());
        var orderSagaData = fixture.Build<OrderSagaData>()
            .With(x => x.OrderId, "orderId")
            .With(x => x.DramaProperty, "NONE")
            .Create();
        var handler = fixture.Build<TransactionSagaHander>().With(saga => saga.Data, orderSagaData).Create();

        var testableSaga = new TestableSaga<TransactionSagaHander, OrderSagaData>(sagaFactory: () => handler);

        var step2Order = fixture.Build<Step2Order>().With(x => x.OrderId, "orderId").Create();
        var context = new TestableMessageHandlerContext();

        // i should be able to run this test picking up from step2,
        //		step2order -> completeOrder
        // so i do not have to construct the whole scenario,
        //		startOrder -> step1Order -> step2order -> completeOrder
        //
        // but this test throws,
        //     System.Exception : Saga not found and message type NsbTesting.Step2Order is not allowed to start the saga.
        // this helps to slice the tests into small scenarios versus havin to repeat the scearnios leading up to step2
        var startOrderResult = await testableSaga.Handle(step2Order, context);

        var orderSagaDataSnapshot = startOrderResult.SagaDataSnapshot;

        Assert.AreEqual("orderId", orderSagaDataSnapshot.OrderId);
        Assert.AreEqual("Step2Order", orderSagaDataSnapshot.DramaProperty);

        var completeOrder = startOrderResult.FindSentMessage<CompleteOrder>();
        Assert.IsNotNull(completeOrder);
        Assert.AreEqual("orderId", completeOrder.OrderId);
    }
```

Exception:

```
  Message: 
System.Exception : Saga not found and message type NsbTesting.Step2Order is not allowed to start the saga.

  Stack Trace: 
TestableSaga`2.LoadSagaData(QueuedSagaMessage message, SynchronizedStorageSession session, TestableMessageHandlerContext context) line 304
TestableSaga`2.InnerHandle(QueuedSagaMessage message, String handleMethodName, TestableMessageHandlerContext context) line 213
TransactionSagaTests.__Verify_Transaction_SagaData_Using_Testing_Previously() line 288
GenericAdapter`1.GetResult()
AsyncToSyncAdapter.Await(Func`1 invoke)
TestMethodCommand.RunTestMethod(TestExecutionContext context)
TestMethodCommand.Execute(TestExecutionContext context)
<>c__DisplayClass4_0.<PerformWork>b__0()
<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
ContextUtils.DoIsolated(ContextCallback callback, Object state)
ContextUtils.DoIsolated[T](Func`1 func)
SimpleWorkItem.PerformWork()
```

#### Additional information

See code for repro at branch:

https://github.com/rmandvikar/delegating-handlers/commit/nsb-saga-testing

**Comment by DavidBoike** [comment]
Hi @rmandvikar,

This isn't a bug, you're just using the wrong class for what you're trying to do.

The `TestableSaga` class is part of the [saga scenario testing](https://docs.particular.net/nservicebus/testing/saga-scenario-testing) framework that emulates how NServiceBus handles saga messages, including an in-memory saga store. That's for testing complete flows without worrying about the internals of how NServiceBus handles the messages or populates finds the saga or fills the `Data` class.

What you are trying to do is a more classic [unit test on a saga handler](https://docs.particular.net/samples/unit-testing/#testing-a-saga) where you'd construct the saga class, fill the `Data` property with the preconditions for the handler, and then assert on the results.

**Comment by DavidBoike** [comment]
Or alternatively, if you want to test the Step2 without reconstructing things, you could lean into the scenario testing model.

In that case you would not want to do this:

```csharp
var testableSaga = new TestableSaga<TransactionSagaHander, OrderSagaData>(sagaFactory: () => handler);
```

Specifically, `sagaFactory: () => handler)` becuase that should not be returning a single instance. The `sagaFactory` parameter is for filling in constructor dependencies of the saga class in lieu of dependency injection.

Then you could build methods in your test fixture for running Step1 and Step2 so that you could compose different flows in different tests to model where Step 1 fails, where Step 1 passes but step 2 fails, etc.

**Comment by rmandvikar** [comment]
> Or alternatively, if you want to test the Step2 without reconstructing things, you could lean into the scenario testing model.

Could you please give a concrete example? My team and I are struggling with this. 

Let's take this for example, where I've changed the the `Handler(StartOrder)`, `Handle(Step1Order)` to include some logic. 

How do we directly unit-test the `Handle(Step1Order)` method by mocking some properties of `SagaData`? We are seeing that the mocked properties of `SagaData` are reset by the `NServiceBus.Testing` `.Handle()` method. Is there a way / workaround by using the `Func<TSaga> sagaFactory` arg in `public TestableSaga(Func<TSaga> sagaFactory = null, DateTime? initialCurrentTime = null)`? The `sagaFactory` is a handler with the `SagaData`. 

Is that a bug or a design decision? See https://docs.particular.net/nservicebus/testing/saga-scenario-testing#handling-messages.

> Every time it is asked to handle a message, the testable saga instantiates a new instance of the saga class and use the mapping information in the ConfigureHowToFindSaga method to locate the correct saga data in the internal storage.

```cs
    public async Task Handle(StartOrder message, IMessageHandlerContext context)
    {
        Data.DramaProperty = "StartOrder";

        // work

        // conditionally set based on some logic
        // HACK hard-code for brevity
        if (true)
        {
            Data.DramaProperty = "something ...";
        }
        else
        {
            Data.DramaProperty = "something different...";
        }

        await context.Send(
            new Step1Order()
            {
                OrderId = message.OrderId
            });
    }

    public async Task Handle(Step1Order message, IMessageHandlerContext context)
    {
        // work

        if (Data.DramaProperty == "StartOrder")
        {
            // note: set some properties of Data here
            // Data.

            await context.Send(
                new Step2Order()
                {
                    OrderId = message.OrderId
                });
        }
        else
        {
            // note: set some properties of Data here
            // Data.

            // work for undo
        }
    }
```

**Comment by DavidBoike** [comment]
If you want to create a unit test, and be responsible for the saga data as part of the preconditions yourself, then you **do not** use `TestableSaga`. You instantiate the saga class and the data yourself and call the Handle method. This is illustrated in the second code snippet at this deep link: https://docs.particular.net/samples/unit-testing/#testing-a-saga.

`TestableSaga` is part of [scenario testing](https://docs.particular.net/nservicebus/testing/saga-scenario-testing) and then you don't get to set preconditions. It's a higher-level test abstraction where you only get to test as if you were handling NServiceBus messages.
