### ISSUE TITLE
Saga testing issues

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.Testing#7]
Raised by @udidahan
Migrated from by https://github.com/Particular/NServiceBus/issues/2020

I think there are some friction points with the saga testing (even as it is now). I can't do an empty ExpectNotSend or an empty ExpectNotSendLocal. I think the following changes may need to be made.
 
```public Saga<T> ExpectNotSend<TMessage>(Func<TMessage, bool> check)```
 
should be:
 
```public Saga<T> ExpectNotSend<TMessage>(Func<TMessage, bool> check = null)```
 
and 
 
```public Saga<T> ExpectNotSendLocal<TMessage>(Func<TMessage, bool> check)```
 
should be 
 
```public Saga<T> ExpectNotSendLocal<TMessage>(Func<TMessage, bool> check = null)```
 
Please check if there are other methods that are missing the "= null".

**Comment by brunobertechini** [comment]
+1 for this to make sure the Handle method does not send/publish anything unless expected.

**Comment by brunobertechini** [comment]
I've found an issue regarding this (after posting)

https://github.com/Particular/NServiceBus.Testing/issues/4

Bruno

**Comment by timbussmann** [comment]
this issues should be resolved by #63
