### ISSUE TITLE
Pipeline executed during unittesting?

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.Testing#8]
Raised by @yvesgoeleven
Migrated from by https://github.com/Particular/NServiceBus/issues/1868

Looks like the pipeline is invoked during unittesting

http://groups.yahoo.com/neo/groups/nservicebus/conversations/topics/20906

That isn't normal is it?

**Comment by johnsimons** [comment]
This is a big topic, should we open a requirements issue instead, @andreasohlund ?

**Comment by andreasohlund** [comment]
Agreed

**Comment by johnsimons** [comment]
We are working on a plan of attack to tackle issues like this.
