### ISSUE TITLE
NServiceBus.Testing V6 treats message inheritence differently

### ISSUE THREAD

**Issue by feinoujc** [Particular/NServiceBus.Testing#95]
When upgrading to V6, I'm noticing a difference in the way the testing framework locates the appropriate message handler from prior versions. It seems much more strict, and doesn't seem to reflect how the framework would work at runtime.

given messages:

```cs
    public abstract class BaseCommand
    {
    }
    public class Command : BaseCommand
    {
    }
    public interface IMyEvent
    {
    }
    public class MyEvent : IMyEvent
    {
    }
```

this handler

```cs
    public class TestHandler : IHandleMessages<BaseCommand>, IHandleMessages<IMyEvent>
    {
        public Task Handle(BaseCommand message, IMessageHandlerContext context)
        {
            return context.Publish<IMyEvent>();
        }

        public Task Handle(IMyEvent message, IMessageHandlerContext context)
        {
            throw new NotImplementedException("can't handle my event");
        }
    }

```

this test
```cs
    [TestFixture]
    public class TextFixture
    {
        [Test]
        public void HandlesCommand()
        {

            Test.Handler<TestHandler>()
                .ExpectPublish<IMyEvent>()
                .OnMessage(new Command());
         //this test never actually calls the handler, and doesn't fail either :(
        }

        [Test]
        public void HandlesEvent()
        {
            Assert.Throws<NotImplementedException>(() => Test.Handler<TestHandler>()
                .OnMessage(new MyEvent()));
         //this test fails, Handle is never called
        }

    }

```

This scenario works in prior version of the testing framework

**Comment by timbussmann** [comment]
Hey @feinoujc 

Thanks for the repo sample. I'll have a closer look at this and see what we can do about this.

Meanwhile I can suggest you two workarounds:

a.) for the interface messages, use the interface message instead:

        [Test]
        public void HandlesEvent()
        {
            Assert.Throws<NotImplementedException>(() => Test.Handler<TestHandler>()
                .OnMessage<IMyEvent>());
        }

(this doesn't work with the abstract message)

b.) Use classic unit tests:

        [Test]
        public async Task HandlesCommand()
        {
            var context = new TestableMessageHandlerContext();
            var handler = new TestHandler();

            await handler.Handle(new Command(), context);

            Assert.That(context.PublishedMessages.Containing<IMyEvent>().Count(), Is.EqualTo(1));
        }

        [Test]
        public void HandlesEvent()
        {
            var context = new TestableMessageHandlerContext();
            var handler = new TestHandler();

            Assert.ThrowsAsync<NotImplementedException>(() => handler.Handle(new MyEvent(), context));
        }

**Comment by timbussmann** [comment]
This has been fixed by #96 and will be released as version 6.0.1. Thanks @feinoujc for raising this and providing repro samples for it 👍

**Comment by timbussmann** [comment]
6.0.1 is released on nuget.
(I adjusted the issue title to give a better description in the release notes)

**Comment by feinoujc** [comment]
Awesome, thanks for the quick turnaround 👍
