### ISSUE TITLE
Validate best practices on tests

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus.Testing#98]
NServiceBus adds special behaviors validating best practices when sending/publishing messages.
E.g. ensuring that you don't send messages declared as events or that you don't publish messages declared as a command.

As we don't enable NServiceBus features or a regular pipeline for the testing framework, those checks are missing and might cause runtime errors which weren't raised during testing. E.g. see this issue: https://github.com/Particular/NServiceBus.Testing/issues/97 or this https://github.com/Particular/NServiceBus.Testing/issues/37

It could make sense to provide the same (or at least similar) validations when running tests via the testing framework. Note that best practice enforcement in the core also works with convention based messages, not sure whether it makes sense to also consider custom conventions.

Thoughts?

**Comment by danielmarbach** [comment]
On the fence. I see the value but if we go down the route we would also need to consider custom convention in my opinion. But there are already helpful utilities and mechanisms out there to enforce conventions like http://kozmic.net/2012/06/14/using-conventiontests/ (I know a bit old but the principle remains)

**Comment by andreasohlund** [comment]
I don't see the ROI on this, I'd say we close this?
